CaseFileTracker/Controllers/CaseFilesController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CaseFileTracker.Controllers
{
    [Authorize]
    public class CaseFilesController : Controller
    {
        private FileTrackerEntities db = new FileTrackerEntities();

        #region Views

        // GET: CaseFiles
        public ActionResult Index()
        {
            return View(db.CaseFiles.OrderBy(c => c.LastName).ToList());
        }

        // GET: CaseFiles
        [ActionName("IndexFiltered")]
        public ActionResult Index(string term)
        {
            List<CaseFile> caseFiles = db
                .CaseFiles
                .Where(c => c.LastName.Contains(term) || c.FirstName.Contains(term))
                .OrderBy(c => c.LastName)
                .ToList();

            return View("Index", caseFiles);
        }

        // GET: CaseFiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CaseFile caseFile = db.CaseFiles.Find(id);
            if (caseFile == null)
            {
                return HttpNotFound();
            }
            return View(caseFile);
        }

        // GET: CaseFiles/Create
        public ActionResult Create()
        {
            return View();
        }

        #endregion Views

        #region CRUD

        // POST: CaseFiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LastName,FirstName,Middle,DOB,SSN")] CaseFile caseFile)
        {
            if (ModelState.IsValid)
            {
                db.CaseFiles.Add(caseFile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(caseFile);
        }

        // GET: CaseFiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CaseFile caseFile = db.CaseFiles.Find(id);
            if (caseFile == null)
            {
                return HttpNotFound();
            }
            return View(caseFile);
        }

        // POST: CaseFiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LastName,FirstName,Middle,DOB,SSN")] CaseFile caseFile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(caseFile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(caseFile);
        }

        // GET: CaseFiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CaseFile caseFile = db.CaseFiles.Find(id);
            if (caseFile == null)
            {
                return HttpNotFound();
            }
            return View(caseFile);
        }

        // POST: CaseFiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CaseFile caseFile = db.CaseFiles.Find(id);
            db.CaseFiles.Remove(caseFile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion CRUS

        #region Misc

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult Search(string term)
        {
            CaseFile[] results = db
                .CaseFiles
                .Where(c => c.LastName.Contains(term) || c.FirstName.Contains(term))
                .OrderBy(c => c.LastName)
                .ToArray();

            return Json(results, JsonRequestBehavior.AllowGet);

        }

        #endregion Misc
    }
}

CaseFileTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PSS Case File Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PSS Case File Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Case Files", "Index", "CaseFiles")</li>
                        <li>@Html.ActionLink("Requests", "Index", "Requests")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PSS Case File Tracker</p>
        </footer>
    </div>

</body>
</html>

CaseFileTracker/Views/Shared/_S2MSLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S2MS File Repository</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">S2MS File Repository</span>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - S2MS File Repository</p>
        </footer>
    </div>

</body>
</html>