CaseFileTracker/Controllers/RequestsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CaseFileTracker.Controllers
{
    public class RequestsController : Controller
    {
        private FileTrackerEntities db = new FileTrackerEntities();

        #region Views

        [AllowAnonymous]
        public ActionResult GetCaseFile()
        {
            return View();
        }

        // GET: Requests
        public ActionResult Index()
        {
            var requests = db.Requests.Include(r => r.AspNetUser).Include(r => r.CaseFile).Include(r => r.RequestType);
            return View(requests.ToList());
        }

        // GET: Requests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            //ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            //ViewBag.CaseFileID = new SelectList(db.CaseFiles, "ID", "LastName");
            ViewBag.RequestTypeID = new SelectList(db.RequestTypes, "ID", "Description");
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CaseFileID,UserID,RequestedBy,RequestTypeID,DateRequested,Location,DateReceived,DateReturned,Notes")] Request request)
        {
            // Initialize date requested
            request.DateRequested = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Requests.Add(request);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", request.UserID);
            //ViewBag.CaseFileID = new SelectList(db.CaseFiles, "ID", "LastName", request.CaseFileID);
            ViewBag.RequestTypeID = new SelectList(db.RequestTypes, "ID", "Description", request.RequestTypeID);

            return View(request);
        }

        // GET: Requests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", request.UserID);
            ViewBag.CaseFileID = new SelectList(db.CaseFiles, "ID", "LastName", request.CaseFileID);
            ViewBag.RequestTypeID = new SelectList(db.RequestTypes, "ID", "Description", request.RequestTypeID);
            return View(request);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CaseFileID,UserID,RequestedBy,RequestTypeID,DateRequested,Location,DateReceived,DateReturned,Notes")] Request request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", request.UserID);
            ViewBag.CaseFileID = new SelectList(db.CaseFiles, "ID", "LastName", request.CaseFileID);
            ViewBag.RequestTypeID = new SelectList(db.RequestTypes, "ID", "Description", request.RequestTypeID);
            return View(request);
        }

        // GET: Requests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Request request = db.Requests.Find(id);
            db.Requests.Remove(request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion Views

        #region Misc

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult SearchByName(string term)
        {
            CaseFile[] subjects = db
                .CaseFiles
                .Where(r => r.LastName.Contains(term) || r.FirstName.Contains(term))
                .OrderBy(r => r.LastName)
                .ToArray();

            return Json(
                subjects.Select(r => 
                    new { id = r.ID, value = string.Format("{0}, {1}", r.LastName, r.FirstName) }
                ), 
                JsonRequestBehavior.AllowGet
            );
        }

        #endregion Misc
    }
}

CaseFileTracker/Views/Requests/Create.cshtml
@model CaseFileTracker.Request

<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $("#SubjectName").autocomplete({
            minLength: 2,
            source: function (request, response) {
                var url = $(this.element).data("url");
                $.getJSON(url, { term: request.term }, function (data) {
                    response(data);
                })
            },
            select: function (event, ui) {
                $("#SubjectName").val(ui.item.value);
                $("#CaseFileID").val(ui.item.id);
                return false;
            }
        });
    });
</script>

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(
                    model => model.SubjectName,
                     new { @class = "form-control ui-autocomplete-input", data_url = Url.Action("SearchByName", "Requests") }
                )
                @Html.ValidationMessageFor(model => model.CaseFileID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">User</label>
            @Html.LabelFor(model => model.AspNetUser.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" disabled="disabled" type="text" value="@User.Identity.Name" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestTypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateReceived, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateReceived, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateReceived, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateReturned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateReturned, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateReturned, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <input id="UserID" type="hidden" value="@Membership.GetUser(User.Identity.Name).ProviderUserKey" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" type="text/css" />
}

CaseFileTracker/Views/Requests/Delete.cshtml
@model CaseFileTracker.Request

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateRequested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateRequested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReceived)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReceived)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReturned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReturned)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaseFile.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaseFile.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestType.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestType.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CaseFileTracker/Views/Requests/Details.cshtml
@model CaseFileTracker.Request

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateRequested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateRequested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReceived)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReceived)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReturned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReturned)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaseFile.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaseFile.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestType.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestType.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CaseFileTracker/Views/Requests/Edit.cshtml
@model CaseFileTracker.Request

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CaseFileID, "CaseFileID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CaseFileID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CaseFileID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestTypeID, "RequestTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateRequested, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateRequested, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateRequested, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateReceived, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateReceived, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateReceived, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateReturned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateReturned, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateReturned, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CaseFileTracker/Views/Requests/GetCaseFile.cshtml
@using System.Web.Configuration;

@{
    Layout = "~/Views/Shared/_S2MSLayout.cshtml";

    string subjectName = "Name not found";
    
    if (Request.QueryString.AllKeys.Contains("name"))
    {
        subjectName = Request["name"].ToString();
    }
}

<script type="text/javascript">

    $(function () {

        var url = "@WebConfigurationManager.AppSettings["xiftServiceUrl"]?uniqueid=@Request["uniqueid"]&ssn=@Request["ssn"]&dob=@Request["dob"]";

        //$.getJSON(url)
        //    .done(function (data) {
        //        $.each(function (index, item) {
        //            $("#fileListing").append("<li>" + item.fileName + "</li>");
        //        });
        //    })
        //    .error(function () {
        //        $("#fileListing").append("<li>Invalid request</li>");
        //    });

        $.ajax({
            url: "@WebConfigurationManager.AppSettings["xiftServiceUrl"]?uniqueid=@Request["uniqueid"]&ssn=@Request["ssn"]&dob=@Request["dob"]",
            type: "GET",
            dataType: "jsonp",
            contentType: "application/json",
            callback: "processFiles"
        //})
        //.success(function (data) {
        //    $.each(function (index, item) {
        //        $("#fileListing").append("<li>" + item.fileName + "</li>");
        //    });
        //})
        //.error(function (xhr, status, err) {
        //    $("#fileListing").append("<li>Invalid request</li>");
        });

    });

    function processFiles(data) {
        alert(data);
    }

</script>

<h4>Case Files for: <b>@subjectName</b></h4>

<br />

<ul id="fileListing"></ul>

<br /><br />

CaseFileTracker/Views/Requests/Index.cshtml
@model IEnumerable<CaseFileTracker.Request>

@{
    ViewBag.Title = "Requests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RequestedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateRequested)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateReceived)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateReturned)
        </th>
        <th>Subject Last</th>
        <th>Subject First</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RequestedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateRequested)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateReceived)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateReturned)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CaseFile.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CaseFile.FirstName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>